### ISSUE TITLE
Possibility to create rules for "absence of code"

### ISSUE THREAD

**Issue by htrgouvea** [htrgouvea/zarn#16]
Currently ZARN works by searching for the presence of dangerous functions/that may present risks and trying to infer whether they are "reachable" through user input. But there are some categories of vulnerabilities/risks that occur through the absence of a code (or a combination of both factors), example: #14

It would be interesting to have an implementation of this feature.

**Comment by htrgouvea** [comment]
Example:

```yaml
  - id: '0005'
    category: warn
    name: "Lorem Ipsum"
    message: "Lorem Ipsum"
    type: presence
    sample:
      - md5
   - id: '0006'
    category: warn
    name: "Other rule"
    message: "Other message"
    type: absence
    sample:
      - strict
      - warnings
```

For rules with type "presence" the current behavior remains the same. For the "absence" rules, the search will be carried out for the absence of the item.
